name: dangr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.0.1

  # Maps
  maplibre_gl: ^0.18.3

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.15.3

  # Network
  dio: ^5.4.0

  # UI/UX
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4

  # Monitoring
  sentry_flutter: ^7.16.1

  # Location
  geolocator: ^10.1.0
  geofence_service: ^2.0.1
  flutter_foreground_task: ^6.1.2
  permission_handler: ^11.1.0

  # Storage
  shared_preferences: ^2.2.2

  # Real-time
  web_socket_channel: ^2.4.0

  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Security
  cryptography: ^2.7.0

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/l10n/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
